//
//  FilmePresenter.swift
//  ProjetoVIPBootcamp
//
//  Created by Fernanda Perovano on 13/10/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresenterInPut {
    func fetchMovies()
}
protocol MoviesPresenterOutput {
    func displayMovies(movies: [Movies])
    func displayError(message: String)
}

class FilmePresenter: MoviesPresenterInPut, MoviesInteractorOutput {
    
    var view: MoviesPresenterOutput?
    var interactor = FilmeInteractor()

    
    func fetchMovies() {
        interactor.fetchMovies()
    }
    
    func moviesFetched(movies: [Movies]) {
        view?.displayMovies(movies: movies)
    }
    
    func moviesFetchFailed(error: Error) {
        view?.displayError(message: error.localizedDescription)
    }
}
